Add get-inactive-issues
coala/scripts pull request #2
Opened 2018-03-08 21:42 UTC by RaiVaibhav

Added `Get all inactive issues list on a repository` Script

2018-03-18 13:51 UTC, adtac requested changes

2018-03-18 13:51 UTC, adtac commented on get-inactive-issues/README.md
> +2. `python-dateutil`.
This isn't formatted properly. See https://github.com/RaiVaibhav/scripts/blob/f934ee20df3fa835d3d8f0cd5819ac08e50ed83f/get-inactive-issues/README.md

Also, instead of this, just add a `requirements.txt` file and ask them to install using `-r requirements.txt` like we do in coala/coala.

2018-03-18 13:51 UTC, adtac commented on get-inactive-issues/README.md
> +## How Does It work
This section isn't required. Remove it. It's a single script; if they want to know how it works, they'll read the source.

2018-03-18 13:51 UTC, adtac commented on get-inactive-issues/README.md
> + text file.
Add instructions on how to run this script. Add information about what goes into `github_token.py`.

2018-03-18 13:51 UTC, adtac commented on .gitignore
> +github_token.py
Force add a sample `github_token.py` with dummy tokens so that the user will know what to fill later.

2018-03-18 13:51 UTC, adtac commented on get-inactive-issues/README.md
> +any activity in 2+ months(You can change it accordingly).
Make this 2+ months configurable as a command line argument?

2018-03-18 13:51 UTC, adtac commented on get-inactive-issues/myscript3.py
> +#add github `FUTHUB_TOKEN` (string)
NOOOO, use a `github_token.py` file and source that file with a `from github_token import TOKEN` and use TOKEN.

2018-03-18 13:51 UTC, adtac commented on get-inactive-issues/myscript3.py
> +thefile = open('test2.txt', 'w')
Make these arguments please.

Use `argparse`.

2018-03-18 13:51 UTC, adtac commented on get-inactive-issues/myscript3.py
> +print time.clock() - start
This is not valid python3. Yet the README says it's compatible with both. Stick to just python3. Python2 is dead.

2018-03-18 13:51 UTC, adtac commented on get-inactive-issues/myscript3.py
> +                    if calculated_days>=60: # for checking last commit update
Configurable

2018-03-18 13:51 UTC, adtac commented on get-inactive-issues/myscript3.py
> +            if c>=60: # for checking assigned duration
Don't repeat the same constant in multiple places. Create a variable (that you can you give through argparse) and use it.

2018-03-18 13:51 UTC, adtac commented on get-inactive-issues/myscript3.py
> +        elif myevents == 'assigned':
No need for `elif` and indentation if the `if` clause will only break. Is there anything other than `assigned` and `unassigned`?

If not:

```py
if something:
    break

the_other_thing()
```

2018-03-18 13:51 UTC, adtac commented on get-inactive-issues/myscript3.py
> +thefile = open('test2.txt', 'w')
And use a better name instead of `thename` lol. Use `f`.

2018-03-18 13:54 UTC, RaiVaibhav commented
Will sort all after this week

2018-04-07 11:31 UTC, jayvdb commented
Could you re-do this and https://github.com/coala/scripts/pull/3 over at https://gitlab.com/coala/junk/scripts ; we're trying to reduce the number of repos on github , as they are better organised with folders over on gitlab.  `junk` is not a reflection on the contents, but rather our lack of care about the contents of the repo, perfect for quick scripts that should be dumped somewhere, and improved only if they become more useful and integrated into our processes.

2018-04-07 11:31 UTC, closed without merging

2018-04-07 11:34 UTC, jayvdb commented
(also this was uploaded into the community repo, so maybe that is enough, im not sure)

2018-04-07 12:11 UTC, RaiVaibhav commented
Yes I also think it's enough :+1: